### PR TITLE
fix canonical URL

### PR DESCRIPTION
**Pull request by andrewtpham**
- adjusted canonical URL based on a change in the original blog url

### CODE REVIEW

**Comment by malakumar85** [comment]
@andrewtpham - can you make the changes to the files in this sub-directory: https://github.com/MERLTech/MERL-Center-public/tree/main/_caseStudies. The files in `learning-content` will be deleted soon.

**Comment by andrewtpham** [comment]
> @andrewtpham - can you make the changes to the files in this sub-directory: https://github.com/MERLTech/MERL-Center-public/tree/main/_caseStudies. The files in `learning-content` will be deleted soon.

@malakumar85 This is ready to be merged. Updated the URLs in the `_case_studies` folder.  You can delete the `learning_content` files now.

**Comment by andrewtpham** [comment]
@malakumar85 can you grant me `write` access so I can resolve the conflict?

**Comment by malakumar85** [comment]
> @malakumar85 can you grant me `write` access so I can resolve the conflict?

Sure, you're on the editor team now with write access

**Comment by andrewtpham** [comment]
Resolved conflicts, this should be ready to be merged

**Review by malakumar85 — APPROVED** [review]
looks good, thanks for the edits!

**Pull request merged**
